FROM mariadb
LABEL   maintainer="Mohammed Ziad" \
	email1="Mohammedziad599@gmail.com" \
	email2="Mohammed.ziad@stu.najah.edu0"

ENV MYSQL_ROOT_PASSWORD=Mohammed
ENV MYSQL_USER=wpuser 
ENV MYSQL_PASSWORD=Mohammed
ENV MYSQL_DATABASE=wordpress_db
VOLUME /var/lib/mysql
RUN cd ~
RUN 
