version: "3.3"

services:
  db:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - ../mysqldb:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    networks:
      - connect
    env_file: ./mysqldb.env
  web-server:
    container_name: webserver
    image: php:7.2.30-apache-buster
    volumes:
      - ../php/:/var/www/html/
    restart: always
    depends_on:
      - db
    ports:
      - 80:80
    networks:
      - connect
    links:
      - "db:database"
    env_file: ./web-server.env
networks:
  connect:
    driver: bridge
